apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: customer-service-prod-v1
  title: Customer Service API v1 - PROD
  description: Customer Service API version 1 - Production
  tags:
    - customer
    - prod
spec:
  type: openapi
  lifecycle: production
  owner: group:platform-team
  definition:
    $text: https://api.example.company.com/customer/v1/swagger.json
